[package]
name = "serde_gvariant"
version = "0.0.1"
authors = ["Luca Bruno <luca.bruno@coreos.com>"]

[dependencies]
byteorder = "1"
serde = "1"
error-chain = {version = "0.11", default-features = false}


[dev-dependencies]
proptest = "0.7"
serde_bytes = "0.10"